### ISSUE TITLE
Zipline returning error on bundle ingestion

### ISSUE THREAD

**Issue by ScottStevenson** [FlorianWilhelm/zipline-poloniex#1]
Running:
Python 3.6.1
zipline==1.1.0
zipline-poloniex==0.1.1

When running the command "zipline ingest -b poloniex" I get the following error and stack trace:

Traceback (most recent call last):
  File "/Users/mbpro/dev/personal/pennant/venv/bin/zipline", line 11, in <module>
    sys.exit(main())
  File "/Users/mbpro/dev/personal/pennant/venv/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/mbpro/dev/personal/pennant/venv/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/mbpro/dev/personal/pennant/venv/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/mbpro/dev/personal/pennant/venv/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/mbpro/dev/personal/pennant/venv/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/mbpro/dev/personal/pennant/venv/lib/python3.6/site-packages/zipline/__main__.py", line 312, in ingest
    show_progress,
  File "/Users/mbpro/dev/personal/pennant/venv/lib/python3.6/site-packages/zipline/data/bundles/core.py", line 451, in ingest
    pth.data_path([name, timestr], environ=environ),
  File "/Users/mbpro/dev/personal/pennant/venv/lib/python3.6/site-packages/zipline_poloniex/bundle.py", line 172, in ingest
    minute_bar_writer.write(data, show_progress=show_progress)
  File "/Users/mbpro/dev/personal/pennant/venv/lib/python3.6/site-packages/zipline/data/minute_bars.py", line 697, in write
    write_sid(*e, invalid_data_behavior=invalid_data_behavior)
  File "/Users/mbpro/dev/personal/pennant/venv/lib/python3.6/site-packages/zipline/data/minute_bars.py", line 730, in write_sid
    self._write_cols(sid, dts, cols, invalid_data_behavior)
  File "/Users/mbpro/dev/personal/pennant/venv/lib/python3.6/site-packages/zipline/data/minute_bars.py", line 791, in _write_cols
    self.pad(sid, day_before_input)
  File "/Users/mbpro/dev/personal/pennant/venv/lib/python3.6/site-packages/zipline/data/minute_bars.py", line 655, in pad
    new_last_date = self.last_date_in_output_for_sid(sid)
  File "/Users/mbpro/dev/personal/pennant/venv/lib/python3.6/site-packages/zipline/data/minute_bars.py", line 556, in last_date_in_output_for_sid
    return self._session_labels[num_days - 1]
  File "/Users/mbpro/dev/personal/pennant/venv/lib/python3.6/site-packages/pandas/tseries/base.py", line 192, in __getitem__
    val = getitem(key)
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

I have done some digging and found that the Poloniex data is indeed getting pulled, and it looks to be in the correct format. I am not quite sure why the index error is being raised.

**Comment by ScottStevenson** [comment]
Update: The commit to Zipline here (included in 1.1.1) fixes the problem! Issue is resolved. https://github.com/quantopian/zipline/commit/5bea92fc2ff094114b082191d5574f77eba985f2
