### ISSUE TITLE
Poloniex API  403

### ISSUE THREAD

**Issue by TheHooper** [FlorianWilhelm/zipline-poloniex#10]
when i type follow command
###  **zipline ingest -b Poloniex**
I get  403  error. I try to curl this URL. There is no problem.

Traceback (most recent call last):
  File "/anaconda3/envs/env_zipline/bin/zipline", line 11, in <module>
    load_entry_point('zipline==1.3.0', 'console_scripts', 'zipline')()
  File "/anaconda3/envs/env_zipline/lib/python3.5/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/anaconda3/envs/env_zipline/lib/python3.5/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/anaconda3/envs/env_zipline/lib/python3.5/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/anaconda3/envs/env_zipline/lib/python3.5/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/anaconda3/envs/env_zipline/lib/python3.5/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/anaconda3/envs/env_zipline/lib/python3.5/site-packages/zipline/__main__.py", line 348, in ingest
    show_progress,
  File "/anaconda3/envs/env_zipline/lib/python3.5/site-packages/zipline/data/bundles/core.py", line 451, in ingest
    pth.data_path([name, timestr], environ=environ),
  File "/anaconda3/envs/env_zipline/lib/python3.5/site-packages/zipline_poloniex/bundle.py", line 198, in ingest
    asset_df = fetch_assets(asset_pairs)
  File "/anaconda3/envs/env_zipline/lib/python3.5/site-packages/zipline_poloniex/bundle.py", line 54, in fetch_assets
    all_assets = get_currencies()
  File "/anaconda3/envs/env_zipline/lib/python3.5/site-packages/zipline_poloniex/api.py", line 56, in get_currencies
    return call_api('returnCurrencies').transpose()
  File "/anaconda3/envs/env_zipline/lib/python3.5/site-packages/zipline_poloniex/utils.py", line 66, in wrapper
    resp = func(*args, **kwargs)
  File "/anaconda3/envs/env_zipline/lib/python3.5/site-packages/zipline_poloniex/api.py", line 43, in call_api
    r.raise_for_status()
  File "/anaconda3/envs/env_zipline/lib/python3.5/site-packages/requests/models.py", line 939, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://poloniex.com/public?command=returnCurrencies

**Comment by FlorianWilhelm** [comment]
@TheHooper I am sorry to inform you that I no longer actively maintain this project. You could have a look at https://github.com/ccxt/ccxt and try to hack it into zipline. I guess that my API code is outdated and due to an API change at Poloniex it no longer works.
